FROM scala-alpine
LABEL maintainer="Asger Bachmann <asger.g.bachmann@jp.dk>"

ENV VERSION="0.20.0"

ENV ZIP_FILE_NAME="snowplow_stream_enrich_kinesis_${VERSION}.zip" \
    JAR_FILE_NAME="snowplow-stream-enrich-kinesis-${VERSION}.jar"

RUN cd /tmp && \
    wget "https://bintray.com/snowplow/snowplow-generic/download_file?file_path=${ZIP_FILE_NAME}" -O ${ZIP_FILE_NAME} && \
    mkdir /app && \
    unzip ${ZIP_FILE_NAME} -d /app && \
    rm ${ZIP_FILE_NAME}

COPY ./stream-enrich/configuration/config /app/configuration/config
COPY ./stream-enrich/configuration/resolver.json /app/configuration/resolver.json
COPY ./stream-enrich/configuration/enrichments/ /app/configuration/enrichments/

CMD java -jar -Dorg.slf4j.simpleLogger.defaultLogLevel=info /app/${JAR_FILE_NAME} --config /app/configuration/config --resolver file:/app/configuration/resolver.json --enrichments file:/app/configuration/enrichments
