FROM scala-alpine
MAINTAINER Klaus Hebsgaaard <klaus.hebsgaard@jp.dk>, Asger Bachmann <asger.g.bachmann@jp.dk>

COPY ./snowplow/2-collectors/scala-stream-collector/target/scala-2.10/snowplow-stream-collector-0.9.0 /app/snowplow-stream-collector-0.9.0.jar
COPY ./scala-collector/configuration/config /app/configuration/config
CMD /app/snowplow-stream-collector-0.9.0.jar --config /app/configuration/config
