FROM scala-alpine
MAINTAINER Klaus Hebsgaaard <klaus.hebsgaard@jp.dk>, Asger Bachmann <asger.g.bachmann@jp.dk>

COPY ./snowplow/2-collectors/scala-stream-collector/target/scala-2.11/snowplow-stream-collector-0.11.0.jar /app/snowplow-stream-collector-0.11.0.jar
COPY ./scala-collector/configuration/config /app/configuration/config
# As per https://discourse.snowplowanalytics.com/t/error-in-running-scala-stream-collector/1643/3, the official way is
# to run with disableCbor to avoid an error from the AWS SDK.
CMD java -jar -Dcom.amazonaws.sdk.disableCbor /app/snowplow-stream-collector-0.11.0.jar --config /app/configuration/config
